name: Power Platform Export & Tag

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the solution"
        required: true
        default: PPfirstsoultion
      exported_solution_folder:
        description: "Name of the folder where the solution needs to be exported"
        required: true
        default: "exported solutions"
      branch_name:
        description: "Branch to run on (dev/test/prod)"
        required: true
        default: Dev
      managed:
        description: "Export as Managed?"
        required: true
        type: boolean
        default: false
env:
#edit your values here
  ENVIRONMENT_URL: 'https://orgeacfefe8.crm.dynamics.com/'
  CLIENT_ID: 'be16e478-4f72-4c79-a086-0a400d3e4215'
  TENANT_ID: '9e6723d3-eca3-4f1c-9e51-4022bcab3bd2'
jobs:
  export-commit-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required for commit & tag

    steps:
      # 1. Checkout the branch chosen by user
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      # 2. Install Power Platform CLI
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Clean up old solution zip
        run: |
          if [ -f ${{ github.event.inputs.exported_solution_folder }}/${{ github.event.inputs.solution_name }}.zip ]; then
            rm  ${{ github.event.inputs.exported_solution_folder }}/${{ github.event.inputs.solution_name }}.zip
          fi
      - name: Clean up old solution folder
        run: |
          if [ -d ${{ github.event.inputs.exported_solution_folder }}/${{ github.event.inputs.solution_name }} ]; then
            rm -rf ${{ github.event.inputs.exported_solution_folder }}/${{ github.event.inputs.solution_name }}
          fi
     
            
