name: Deploy Power Platform Solution (Dev → UAT)

on:
  workflow_dispatch:   # manually trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Power Platform CLI
      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerPlatform.CLI
          echo "C:\\Users\\runneradmin\\.dotnet\\tools" >> $env:GITHUB_PATH

      # 3. Authenticate to UAT
      - name: Authenticate to UAT
        run: |
          pac auth create `
            --tenant ${{ secrets.POWERPLATFORM_TENANT }} `
            --applicationId ${{ secrets.POWERPLATFORM_CLIENTID }} `
            --clientSecret ${{ secrets.POWERPLATFORM_SECRET }} `
            --environment ${{ secrets.UAT_ENVIRONMENT }}

      # 4. Import Solution to UAT
      - name: Import Solution
        run: |
          pac solution import `
            --path ./solutions/PP-first-soultion.zip `
            --async `
            --activate-plugins `
            --overwrite
